# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  left_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  left_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  left_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  left_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  left_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  left_gripper_joint:
    has_velocity_limits: true
    max_velocity: 1.78
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_effort_limits: true
    max_effort: 5.0
  right_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  right_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  right_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  right_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  right_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  right_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  right_gripper_joint:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_effort_limits: true
    max_effort: 2.2
