kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.08949928559905179
    roll: -0
    pitch: 0
    yaw: 6.935093637945505e-05
  upper_arm:
    x: -4.453187360131969e-05
    y: 0
    z: 0
    roll: 1.569776430478979
    pitch: 0
    yaw: -1.899595783444728e-05
  forearm:
    x: -0.4255955178735976
    y: 0
    z: 0
    roll: 0.003664895000787752
    pitch: 0.003110587533505237
    yaw: -1.094175347315775e-05
  wrist_1:
    x: -0.3924311684839673
    y: -0.0005944496110317049
    z: 0.1111578032629135
    roll: 0.005347748217401119
    pitch: 0.0006785171055329065
    yaw: -2.742538745494148e-05
  wrist_2:
    x: 2.941862599780075e-05
    y: -0.09489788806426759
    z: 0.0001260172312971319
    roll: 1.569468403067662
    pitch: 0
    yaw: -9.542494196330857e-05
  wrist_3:
    x: 2.687562318826077e-05
    y: 0.08246936226018541
    z: 0.0001064480457512508
    roll: 1.572087084765102
    pitch: 3.141592653589793
    yaw: 3.141548784260287
  hash: calib_1333670182501739683